# Generated by Django 6.0.3 on 2026-04-01 11:22

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[courses.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, validators=[courses.models.validate_capital, courses.models.validate_symbol]),
        ),
    ]
